[project]
name = "utils"
version = "0.1.0"
description = "Advent of Code"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["utils"]